### ISSUE TITLE
When confirming order the following error is thrown

### ISSUE THREAD

**Issue by abiwaken** [Evgenii-v/clerkscart#1]
In the latest release their is error when confirming an order

I am using clerkscart Version 2.2.6.4

**Comment by Evgenii-v** [comment]
what exactly  ?

**Comment by abiwaken** [comment]
Paypal checkout goes well until you return to the site to confirm the order. That's when the error is thrown.
![1](https://cloud.githubusercontent.com/assets/24409069/21003949/1b84a774-bd3f-11e6-8f21-cc87953cd014.JPG)
![3](https://cloud.githubusercontent.com/assets/24409069/21003955/22d00758-bd3f-11e6-9771-06a71751551b.JPG)
![4](https://cloud.githubusercontent.com/assets/24409069/21003964/2dd79ec2-bd3f-11e6-83cc-9c866f425173.JPG)
![5](https://cloud.githubusercontent.com/assets/24409069/21003971/365b12b8-bd3f-11e6-9312-2326dfc60c32.JPG)
![6](https://cloud.githubusercontent.com/assets/24409069/21003991/4db10b16-bd3f-11e6-9f1e-ecc78077ddec.JPG)

I am using clerkscart Version 2.2.6.4

**Comment by Evgenii-v** [comment]
It seems that this is a problem with pp_express , until this issue not resolved, you can use pp_standard  with these corrections https://github.com/Evgenii-v/clerkscart/commit/367a2f9e94f185c8a0ecca0d32824df7575e6f3f

**Comment by abiwaken** [comment]
Thank you. Well then i shall settle for the pp-express. I just got started with clerkscart and i am banking on it  as a powerful multivendor shopping cart.
