### ISSUE TITLE
BUG -- Separate seller registration page

### ISSUE THREAD

**Issue by web1989** [Evgenii-v/clerkscart#7]
When a customer registers normally, the administrative panel button (  approve as seller ) does not work, please fix this.
http://clerkscart.com/index.php?route=product/product&path=59&product_id=75

**Comment by web1989** [comment]
check this file catalog/model/account/customer.php  on extension Separate seller registration page

**Comment by Evgenii-v** [comment]
replace catalog/model/account/customer.php to default file from  release , file from  module does not create a seller record for customer -

so you can not  approve as seller.

This function makes a new file catalog/model/account/sellerregister.php

**Comment by claudineireal** [comment]
Solved, thanks.

**Comment by web1989** [comment]
Solved, thanks.
